language: node_js
sudo: false
node_js:
  - 9
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g codecov
script:
  - npm test
after_success:
  - npm run coverage
  - npm run release
